server:
  port: 8181

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: @project.artifactId@
  boot:
    admin:
      client:
        #要注册的server端的url地址。如果有多个，则用逗号分隔
        url: http://localhost:8081/
        instance:
          service-base-url: http://127.0.0.1:8181  #自定义节点的ip地址
          prefer-ip: true  #是否显示真实的ip地址
            #元数据，用于配置monitor server访问client端的凭证
          #metadata:
          # user.name: user
          # user.password: 123456
        #client可以连接到monitor server端的凭证
        username: admin
        password: 123456
        read-timeout: 10000  #读取超时时间
#公开所有的端点
management:
  endpoints:
    web:
      exposure:
        #展示某些端点（默认展示health,info，其余均禁止）
        include: health,info,metrics
      # CORS跨域支持
      cors:
        allowed-origins: "*"
        allowed-methods: GET,POST

  #health端点的访问权限
  endpoint:
    health:
      #选择展示
      show-details: always
  health:
    mail:
      enabled: false  #不监控邮件服务器状态
info:
  app:
    name: @project.artifactId@
  build:
    artifactId: @project.artifactId@
    version: @project.version@
  author:
    name: ken

eureka:
  instance:
    hostname: @project.artifactId@
    appname: @project.artifactId@
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-server:eureka-server@wlhoney-server-1st:8081/eureka/,http://eureka-server:eureka-server@wlhoney-server-2nd:8082/eureka/