server:
  port: 8081
#spring cloud eureka优先使用spring.application.name值来覆盖eureka.instance.appname的值
spring:
  application:
    name: @project.artifactId@

info:
  app:
    name: @project.artifactId@
  build:
    artifactId: @project.artifactId@
    version: @project.version@
  author:
    name: ken

eureka:
  dashboard:
    path: / #default:'/', eureka web ui访问路径
  instance:
    hostname: wlhoney-server-1st
    appname: @project.artifactId@
    preferIpAddress: false
    instance-id: ${eureka.instance.appname}:${server.port}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-server:eureka-server@wlhoney-server-2nd:8082/eureka/
    fetch-registry: true #default:'true' 此客户端是否获取eureka服务器注册表上的注册信息
    register-with-eureka: true #default:'true' 实例是否在eureka服务器上注册自己的信息以供其他服务发现


