
server:
  port: 8080
  servlet:
    context-path: /wlhoney

spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: utf-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  thymeleaf:
    cache: false #缓冲的配置
    check-template: true
    check-template-location: true
    enabled: true  #开启MVC thymeleaf 视图解析
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
#全局属性配置(Canonical names should be kebab-case ('-' separated))
global:
  pageSize: 10
  successOperation: 操作成功
  errorOperation: 操作失败
  uploadPath: C:/WorkSpace/photos/
  fileRequestUrl: /files/**