server:
  port: 8180
  servlet:
    context-path: /wlhoney

spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: utf-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  thymeleaf:
    cache: false #缓冲的配置
    check-template: true
    check-template-location: true
    enabled: true  #开启MVC thymeleaf 视图解析
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    name: test
    url: jdbc:mysql://47.110.153.104:3306/enjoy_life?serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://localhost:3306/enjoy_life?serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 3600000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#全局属性配置(Canonical names should be kebab-case ('-' separated))
global:
  pageSize: 10
  successOperation: 操作成功
  errorOperation: 操作失败
  fileUploadPath: C:/WorkSpace/photos/
  fileRequestUrl: /files/**