server:
  port: 8180
  servlet:
    context-path: /wlhoney

spring:
  http:
    encoding:
      force: true
      enabled: true
      charset: utf-8
  thymeleaf:
    cache: false #缓冲的配置
    check-template: true
    check-template-location: true
    enabled: true  #开启MVC thymeleaf 视图解析
    encoding: utf-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

#全局属性配置(Canonical names should be kebab-case ('-' separated))
global:
  pageSize: 10
  successOperation: 操作成功
  errorOperation: 操作失败
  fileUploadPath: C:/WorkSpace/photos/
  fileRequestUrl: /files/**

eureka:
  instance:
    hostname: @project.artifactId@
    appname: wlhoney-consume-ribbon
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${server.port}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-server:eureka-server@wlhoney-server-1st:8081/eureka/, http://eureka-server:eureka-server@wlhoney-server-2nd:8082/eureka/