server:
  port: 8082

info:
  app:
    name: @project.artifactId@
  build:
    artifactId: @project.artifactId@
    version: @project.version@
  author:
    name: ken

eureka:
  dashboard:
    path: / #default '/'
  instance:
    hostname: wlhoney-server-2nd
    appname: @project.artifactId@
    preferIpAddress: false
    instance-id: ${eureka.instance.appname}:${server.port}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-server:eureka-server@wlhoney-server-1st:8081/eureka/

