server:
  port: 8082

#spring cloud eureka优先使用spring.application.name值来覆盖eureka.instance.appname的值
eureka:
  instance:
    hostname: wlhoney-server-2nd
    appname: wlhoney-server
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://wlhoney-server-1st:8081/