server:
  port: 8182

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: @project.artifactId@

info:
  app:
    name: @project.artifactId@
  build:
    artifactId: @project.artifactId@
    version: @project.version@
  author:
    name: ken

eureka:
  instance:
    hostname: wlhoney-album
    appname: @project.artifactId@
    prefer-ip-address: true
    instance-id: ${eureka.instance.appname}:${server.port}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-server:eureka-server@wlhoney-server-1st:8081/eureka/, http://eureka-server:eureka-server@wlhoney-server-2nd:8082/eureka/