server:
  port: 8183

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

eureka:
  instance:
    hostname: wlhoney-album
    appname: wlhoney-album
    prefer-ip-address: true
    client:
      healthcheck:
        enabled: true
      service-url:
        defaultZone: http://admin:admin@wlhoney-photo:8182

info:
  app:
    name: wlhoney-album