server:
  port: 8081

eureka:
  instance:
    hostname: wlhoney-server-first
    appname: wlhoney-server
    preferIpAddress: false
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://wlhoney-server-second:8082/