server:
  port: 8081

spring:
  application:
    name: wlhoney-server

eureka:
  instance:
    hostname: wlhoney-server-first
    appname: wlhoney-server-first
    prefer-ip-address: false
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://wlhoney-server-second:8082

info:
  app:
    name: wlhoney-server-first