server:
  port: 8081

eureka:
  instance:
    hostname: wlhoney-server-first
    appname: wlhoney-server
    prefer-ip-address: false
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://wlhoney-server-second:8082