server:
  port: 8182

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

eureka:
  instance:
    hostname: wlhoney-photo
    appname: wlhoney-photo
    prefer-ip-address: true
    client:
      healthcheck:
        enabled: true
      service-url:
        defaultZone: http://admin:admin@wlhoney-album:8183/eureka

info:
  app:
    name: wlhoney-photo