server:
  port: 8181

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  application:
    name: wlhoney-photo

eureka:
  instance:
    hostname: wlhoney-photo
    appname: wlhoney-photo
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-server:eureka-server@wlhoney-server-first:8081/eureka/,http://eureka-server:eureka-server@wlhoney-server-second:8082/eureka/

info:
  app:
    name: wlhoney-photo